/*
 * This file is generated by jOOQ.
*/
package de.warhog.fpvlaptracker.jooq.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Laps implements Serializable {

    private static final long serialVersionUID = -1534204819;

    private final Integer id;
    private final Integer raceid;
    private final Long    chipid;
    private final Integer lap;
    private final Integer duration;

    public Laps(Laps value) {
        this.id = value.id;
        this.raceid = value.raceid;
        this.chipid = value.chipid;
        this.lap = value.lap;
        this.duration = value.duration;
    }

    public Laps(
        Integer id,
        Integer raceid,
        Long    chipid,
        Integer lap,
        Integer duration
    ) {
        this.id = id;
        this.raceid = raceid;
        this.chipid = chipid;
        this.lap = lap;
        this.duration = duration;
    }

    public Integer getId() {
        return this.id;
    }

    public Integer getRaceid() {
        return this.raceid;
    }

    public Long getChipid() {
        return this.chipid;
    }

    public Integer getLap() {
        return this.lap;
    }

    public Integer getDuration() {
        return this.duration;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Laps (");

        sb.append(id);
        sb.append(", ").append(raceid);
        sb.append(", ").append(chipid);
        sb.append(", ").append(lap);
        sb.append(", ").append(duration);

        sb.append(")");
        return sb.toString();
    }
}
