/*
 * This file is generated by jOOQ.
*/
package de.warhog.fpvlaptracker.jooq;


import javax.annotation.Generated;

import org.jooq.Sequence;
import org.jooq.impl.SequenceImpl;


/**
 * Convenience access to all sequences in PUBLIC
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sequences {

    /**
     * The sequence <code>PUBLIC.SYSTEM_SEQUENCE_ACBE0DED_AB09_47F1_ABB9_38D83FDEF82A</code>
     */
    public static final Sequence<Long> SYSTEM_SEQUENCE_ACBE0DED_AB09_47F1_ABB9_38D83FDEF82A = new SequenceImpl<Long>("SYSTEM_SEQUENCE_ACBE0DED_AB09_47F1_ABB9_38D83FDEF82A", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT);

    /**
     * The sequence <code>PUBLIC.SYSTEM_SEQUENCE_FD7D9474_1D79_4002_AF15_F82B395DC783</code>
     */
    public static final Sequence<Long> SYSTEM_SEQUENCE_FD7D9474_1D79_4002_AF15_F82B395DC783 = new SequenceImpl<Long>("SYSTEM_SEQUENCE_FD7D9474_1D79_4002_AF15_F82B395DC783", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT);
}
