/*
 * This file is generated by jOOQ.
*/
package de.warhog.fpvlaptracker.jooq;


import de.warhog.fpvlaptracker.jooq.tables.Config;
import de.warhog.fpvlaptracker.jooq.tables.Laps;
import de.warhog.fpvlaptracker.jooq.tables.Participants;
import de.warhog.fpvlaptracker.jooq.tables.Races;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in PUBLIC
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>PUBLIC.CONFIG</code>.
     */
    public static final Config CONFIG = de.warhog.fpvlaptracker.jooq.tables.Config.CONFIG;

    /**
     * The table <code>PUBLIC.RACES</code>.
     */
    public static final Races RACES = de.warhog.fpvlaptracker.jooq.tables.Races.RACES;

    /**
     * The table <code>PUBLIC.PARTICIPANTS</code>.
     */
    public static final Participants PARTICIPANTS = de.warhog.fpvlaptracker.jooq.tables.Participants.PARTICIPANTS;

    /**
     * The table <code>PUBLIC.LAPS</code>.
     */
    public static final Laps LAPS = de.warhog.fpvlaptracker.jooq.tables.Laps.LAPS;
}
