#language: java
#jdk:
#  - oraclejdk8

#script: "gradle build"

#env:
#  - TRAVIS_NODE_VERSION="7.7"

#before_install:
#  - rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm install $TRAVIS_NODE_VERSION
#  - npm install
  
  
  
matrix:
  include:
    - language: java
      os: linux
      dist: bionic
      jdk:
        - oraclejdk8
      before_install:
        - cd web
        - npm install
      script:
        - cd web
        - gradle build

#    - language: android
#      dist: trusty
#      jdk: oraclejdk8
#      android:
#        components:
#          - tools
#          - android-25
#          - build-tools-25.0.3
#      before_script:
#        - cd android/AppName
#      script:
#        - ./gradlew build connectedCheck
#
#    - language: objective-c
#      os: osx
#      osx_image: xcode8.3
#      before_script:
#        - cd ios/AppName
#      script:
#        - xcodebuild -workspace AppName.xcworkspace -scheme AppName
#          -destination 'platform=iOS Simulator,name=iPhone 7,OS=10.3' build test
