/*
 * This file is generated by jOOQ.
 */
package de.warhog.fpvlaptracker.jooq.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Config implements Serializable {

    private static final long serialVersionUID = 1928565633;

    private final String configKey;
    private final String configValue;

    public Config(Config value) {
        this.configKey = value.configKey;
        this.configValue = value.configValue;
    }

    public Config(
        String configKey,
        String configValue
    ) {
        this.configKey = configKey;
        this.configValue = configValue;
    }

    public String getConfigKey() {
        return this.configKey;
    }

    public String getConfigValue() {
        return this.configValue;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Config (");

        sb.append(configKey);
        sb.append(", ").append(configValue);

        sb.append(")");
        return sb.toString();
    }
}
