/*
 * This file is generated by jOOQ.
 */
package de.warhog.fpvlaptracker.jooq.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Participants implements Serializable {

    private static final long serialVersionUID = -1675511636;

    private final Long   chipid;
    private final String name;

    public Participants(Participants value) {
        this.chipid = value.chipid;
        this.name = value.name;
    }

    public Participants(
        Long   chipid,
        String name
    ) {
        this.chipid = chipid;
        this.name = name;
    }

    public Long getChipid() {
        return this.chipid;
    }

    public String getName() {
        return this.name;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Participants (");

        sb.append(chipid);
        sb.append(", ").append(name);

        sb.append(")");
        return sb.toString();
    }
}
