/*
 * This file is generated by jOOQ.
 */
package de.warhog.fpvlaptracker.jooq.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PersistentLogins implements Serializable {

    private static final long serialVersionUID = -644787252;

    private final String    username;
    private final String    series;
    private final String    token;
    private final Timestamp lastUsed;

    public PersistentLogins(PersistentLogins value) {
        this.username = value.username;
        this.series = value.series;
        this.token = value.token;
        this.lastUsed = value.lastUsed;
    }

    public PersistentLogins(
        String    username,
        String    series,
        String    token,
        Timestamp lastUsed
    ) {
        this.username = username;
        this.series = series;
        this.token = token;
        this.lastUsed = lastUsed;
    }

    public String getUsername() {
        return this.username;
    }

    public String getSeries() {
        return this.series;
    }

    public String getToken() {
        return this.token;
    }

    public Timestamp getLastUsed() {
        return this.lastUsed;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("PersistentLogins (");

        sb.append(username);
        sb.append(", ").append(series);
        sb.append(", ").append(token);
        sb.append(", ").append(lastUsed);

        sb.append(")");
        return sb.toString();
    }
}
