/*
 * This file is generated by jOOQ.
 */
package de.warhog.fpvlaptracker.jooq.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Pilots implements Serializable {

    private static final long serialVersionUID = 1894067737;

    private final String name;
    private final Long   chipid;

    public Pilots(Pilots value) {
        this.name = value.name;
        this.chipid = value.chipid;
    }

    public Pilots(
        String name,
        Long   chipid
    ) {
        this.name = name;
        this.chipid = chipid;
    }

    public String getName() {
        return this.name;
    }

    public Long getChipid() {
        return this.chipid;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Pilots (");

        sb.append(name);
        sb.append(", ").append(chipid);

        sb.append(")");
        return sb.toString();
    }
}
