/*
 * This file is generated by jOOQ.
 */
package de.warhog.fpvlaptracker.jooq.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Profiles implements Serializable {

    private static final long serialVersionUID = -782809469;

    private final Long   chipid;
    private final String name;
    private final String data;

    public Profiles(Profiles value) {
        this.chipid = value.chipid;
        this.name = value.name;
        this.data = value.data;
    }

    public Profiles(
        Long   chipid,
        String name,
        String data
    ) {
        this.chipid = chipid;
        this.name = name;
        this.data = data;
    }

    public Long getChipid() {
        return this.chipid;
    }

    public String getName() {
        return this.name;
    }

    public String getData() {
        return this.data;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Profiles (");

        sb.append(chipid);
        sb.append(", ").append(name);
        sb.append(", ").append(data);

        sb.append(")");
        return sb.toString();
    }
}
