/*
 * This file is generated by jOOQ.
 */
package de.warhog.fpvlaptracker.jooq.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Races implements Serializable {

    private static final long serialVersionUID = 1737941247;

    private final Integer id;
    private final Integer starttime;
    private final Integer laps;
    private final String  state;

    public Races(Races value) {
        this.id = value.id;
        this.starttime = value.starttime;
        this.laps = value.laps;
        this.state = value.state;
    }

    public Races(
        Integer id,
        Integer starttime,
        Integer laps,
        String  state
    ) {
        this.id = id;
        this.starttime = starttime;
        this.laps = laps;
        this.state = state;
    }

    public Integer getId() {
        return this.id;
    }

    public Integer getStarttime() {
        return this.starttime;
    }

    public Integer getLaps() {
        return this.laps;
    }

    public String getState() {
        return this.state;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Races (");

        sb.append(id);
        sb.append(", ").append(starttime);
        sb.append(", ").append(laps);
        sb.append(", ").append(state);

        sb.append(")");
        return sb.toString();
    }
}
