/*
 * This file is generated by jOOQ.
 */
package de.warhog.fpvlaptracker.jooq.tables;


import de.warhog.fpvlaptracker.jooq.Indexes;
import de.warhog.fpvlaptracker.jooq.Keys;
import de.warhog.fpvlaptracker.jooq.Public;
import de.warhog.fpvlaptracker.jooq.tables.records.LapsRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Laps extends TableImpl<LapsRecord> {

    private static final long serialVersionUID = -1609458729;

    /**
     * The reference instance of <code>PUBLIC.LAPS</code>
     */
    public static final Laps LAPS = new Laps();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<LapsRecord> getRecordType() {
        return LapsRecord.class;
    }

    /**
     * The column <code>PUBLIC.LAPS.ID</code>.
     */
    public final TableField<LapsRecord, Integer> ID = createField("ID", org.jooq.impl.SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>PUBLIC.LAPS.RACEID</code>.
     */
    public final TableField<LapsRecord, Integer> RACEID = createField("RACEID", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>PUBLIC.LAPS.CHIPID</code>.
     */
    public final TableField<LapsRecord, Long> CHIPID = createField("CHIPID", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>PUBLIC.LAPS.LAP</code>.
     */
    public final TableField<LapsRecord, Integer> LAP = createField("LAP", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>PUBLIC.LAPS.DURATION</code>.
     */
    public final TableField<LapsRecord, Integer> DURATION = createField("DURATION", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * Create a <code>PUBLIC.LAPS</code> table reference
     */
    public Laps() {
        this(DSL.name("LAPS"), null);
    }

    /**
     * Create an aliased <code>PUBLIC.LAPS</code> table reference
     */
    public Laps(String alias) {
        this(DSL.name(alias), LAPS);
    }

    /**
     * Create an aliased <code>PUBLIC.LAPS</code> table reference
     */
    public Laps(Name alias) {
        this(alias, LAPS);
    }

    private Laps(Name alias, Table<LapsRecord> aliased) {
        this(alias, aliased, null);
    }

    private Laps(Name alias, Table<LapsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> Laps(Table<O> child, ForeignKey<O, LapsRecord> key) {
        super(child, key, LAPS);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.PRIMARY_KEY_9);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<LapsRecord, Integer> getIdentity() {
        return Keys.IDENTITY_LAPS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<LapsRecord> getPrimaryKey() {
        return Keys.PK_LAPS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<LapsRecord>> getKeys() {
        return Arrays.<UniqueKey<LapsRecord>>asList(Keys.PK_LAPS, Keys.UQ_LAPS);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Laps as(String alias) {
        return new Laps(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Laps as(Name alias) {
        return new Laps(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Laps rename(String name) {
        return new Laps(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Laps rename(Name name) {
        return new Laps(name, null);
    }
}
