/*
 * This file is generated by jOOQ.
*/
package de.warhog.fpvlaptracker.jooq.tables;


import de.warhog.fpvlaptracker.jooq.Keys;
import de.warhog.fpvlaptracker.jooq.Public;
import de.warhog.fpvlaptracker.jooq.tables.records.LapsRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Laps extends TableImpl<LapsRecord> {

    private static final long serialVersionUID = 1916906721;

    /**
     * The reference instance of <code>PUBLIC.LAPS</code>
     */
    public static final Laps LAPS = new Laps();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<LapsRecord> getRecordType() {
        return LapsRecord.class;
    }

    /**
     * The column <code>PUBLIC.LAPS.ID</code>.
     */
    public final TableField<LapsRecord, Integer> ID = createField("ID", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.field("(NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_FD7D9474_1D79_4002_AF15_F82B395DC783)", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>PUBLIC.LAPS.RACEID</code>.
     */
    public final TableField<LapsRecord, Integer> RACEID = createField("RACEID", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>PUBLIC.LAPS.CHIPID</code>.
     */
    public final TableField<LapsRecord, Integer> CHIPID = createField("CHIPID", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>PUBLIC.LAPS.LAP</code>.
     */
    public final TableField<LapsRecord, Integer> LAP = createField("LAP", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>PUBLIC.LAPS.DURATION</code>.
     */
    public final TableField<LapsRecord, Integer> DURATION = createField("DURATION", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * Create a <code>PUBLIC.LAPS</code> table reference
     */
    public Laps() {
        this("LAPS", null);
    }

    /**
     * Create an aliased <code>PUBLIC.LAPS</code> table reference
     */
    public Laps(String alias) {
        this(alias, LAPS);
    }

    private Laps(String alias, Table<LapsRecord> aliased) {
        this(alias, aliased, null);
    }

    private Laps(String alias, Table<LapsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<LapsRecord, Integer> getIdentity() {
        return Keys.IDENTITY_LAPS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<LapsRecord> getPrimaryKey() {
        return Keys.PK_LAPS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<LapsRecord>> getKeys() {
        return Arrays.<UniqueKey<LapsRecord>>asList(Keys.PK_LAPS, Keys.UQ_LAPS);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Laps as(String alias) {
        return new Laps(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Laps rename(String name) {
        return new Laps(name, null);
    }
}
