/*
 * This file is generated by jOOQ.
 */
package de.warhog.fpvlaptracker.jooq;


import de.warhog.fpvlaptracker.jooq.tables.Config;
import de.warhog.fpvlaptracker.jooq.tables.Laps;
import de.warhog.fpvlaptracker.jooq.tables.PersistentLogins;
import de.warhog.fpvlaptracker.jooq.tables.Pilots;
import de.warhog.fpvlaptracker.jooq.tables.Profiles;
import de.warhog.fpvlaptracker.jooq.tables.Races;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in PUBLIC
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>PUBLIC.CONFIG</code>.
     */
    public static final Config CONFIG = de.warhog.fpvlaptracker.jooq.tables.Config.CONFIG;

    /**
     * The table <code>PUBLIC.LAPS</code>.
     */
    public static final Laps LAPS = de.warhog.fpvlaptracker.jooq.tables.Laps.LAPS;

    /**
     * The table <code>PUBLIC.PERSISTENT_LOGINS</code>.
     */
    public static final PersistentLogins PERSISTENT_LOGINS = de.warhog.fpvlaptracker.jooq.tables.PersistentLogins.PERSISTENT_LOGINS;

    /**
     * The table <code>PUBLIC.PILOTS</code>.
     */
    public static final Pilots PILOTS = de.warhog.fpvlaptracker.jooq.tables.Pilots.PILOTS;

    /**
     * The table <code>PUBLIC.PROFILES</code>.
     */
    public static final Profiles PROFILES = de.warhog.fpvlaptracker.jooq.tables.Profiles.PROFILES;

    /**
     * The table <code>PUBLIC.RACES</code>.
     */
    public static final Races RACES = de.warhog.fpvlaptracker.jooq.tables.Races.RACES;
}
